# Generated by Django 4.0.3 on 2022-04-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiretap', '0002_message_interaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='interaction_id',
        ),
        migrations.RemoveField(
            model_name='tap',
            name='mask_chd',
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
