# Generated by Django 4.0.3 on 2022-03-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censoredwords',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
