# Generated by Django 4.0.3 on 2022-03-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_censoredwords_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censoredwords',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
