# Generated by Django 4.0.3 on 2022-03-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_censoredwords_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='censoredwords',
            old_name='word_list',
            new_name='document_text',
        ),
        migrations.RemoveField(
            model_name='censoredwords',
            name='active',
        ),
        migrations.RemoveField(
            model_name='censoredwords',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='censoredwords',
            name='word_identifier',
        ),
        migrations.AddField(
            model_name='censoredwords',
            name='filtered_words',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
